### ISSUE TITLE
option._pattern is not a function

### ISSUE THREAD

**Issue by rshade** [arrowrowe/textlint-rule-editorconfig#5]
I am getting the following error on a markdown, any idea where to look to correct this? 
`option._pattern is not a function
at plugins\node_modules\braces\README.md

× Stack trace
TypeError: option._pattern is not a function
    at loopRoot (plugins\node_modules\textlint-rule-editorconfig\editorconfig\get-config.js:10:16)
    at module.exports (plugins\node_modules\textlint-rule-editorconfig\editorconfig\loop-root.js:10:5)
    at getRoot.then (plugins\node_modules\textlint-rule-editorconfig\editorconfig\get-config.js:9:3)
    at tryCatcher (plugins\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (plugins\node_modules\bluebird\js\release\promise.js:503:31)
    at Promise._settlePromise (plugins\node_modules\bluebird\js\release\promise.js:560:18)
    at Promise._settlePromise0 (plugins\node_modules\bluebird\js\release\promise.js:605:10)
    at Promise._settlePromises (plugins\node_modules\bluebird\js\release\promise.js:684:18)
    at Async._drainQueue (plugins\node_modules\bluebird\js\release\async.js:126:16)
    at Async._drainQueues (plugins\node_modules\bluebird\js\release\async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (plugins\node_modules\bluebird\js\release\async.js:16:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

**Comment by rshade** [comment]
looks like this might be a node version issue. I am closing.
